- Cargo.lock
- src/cli.rs
- src/fs/erdtree/mod.rs
- src/fs/erdtree/node.rs
- src/fs/erdtree/order.rs
- src/fs/erdtree/tree/mod.rs
- src/fs/erdtree/tree/test.rs
- src/fs/error.rs
- src/fs/file_size.rs
1. Refactored the code according to `cargo clippy` and fixed some redundant things, such as calling `.as_str()` on the format-macro, when you can instead use `&format!("...")`
2. Ran `cargo update` - https://doc.rust-lang.org/cargo/commands/cargo-update.html
3. Formatted the code to the style defined in rust-analyzer/cargo fmt
> Minor refactoring and cleanup

- .github/workflows/publish.yml
github actions log: 
[jobs/7093543725](https://github.com/Tlntin/erdtree/actions/runs/4110580480/jobs/7093543725)
release:
[binnary download](https://github.com/Tlntin/erdtree/releases/tag/v1.0.0)
> support auto build binnary with github actions

- CHANGELOG.md
- Cargo.toml
- README.md
- src/cli.rs
- src/fs/erdtree/tree/mod.rs
- src/main.rs
- tests/glob.rs
- Using argument names that are more aligned with tools like `exa`, `rg`, etc..
- Shorten binary name to `et`
- Crate metadata update
> Prepare for v1.0 release

- .github/workflows/publish.yml
- .github/workflows/test.yml
1. Change the Docker compilation of aarch64 to cross-platform compilation to speed up compilation.
2. It supports cargo cache and target folder compilation process cache to speed up compilation.
- click Acions
- click Test App With Cache
- click Run workflow.
- The first compilation takes about 7 minutes. After successful compilation, a cache based on the master branch will be generated, so it only takes about 1-3 minutes to compile again.
- When you compile success, go to `Releases`, you will see a tag `Continuous` with pre-release type.
- After you test the compiled product, it is recommended that you delete the test tag, otherwise the compiled result will not be uploaded due to the duplicate name in the next test。
```bash
git push origin :refs/tags/continuous
```
- **Publish.yaml will …
> speed up github action compile

- src/cli.rs
- src/fs/erdtree/mod.rs
- src/fs/erdtree/node.rs
- src/fs/erdtree/order.rs
- src/fs/erdtree/tree/mod.rs
- src/fs/error.rs
- src/icons.rs
- src/main.rs
- Added support for the display of glyphs/icons based on file extensions, special file names (e.g. `.Trash`, `.gitignore`, etc.), and a limited subset of file types.
- Icons are enabled with the `--icons` flag similar to how `exa` does it.
- Some icons were sourced from [exa](https://github.com/ogham/exa/blob/master/src/output/icons.rs) and others along  from [nvim-web-devicons](https://github.com/nvim-tree/nvim-web-devicons).
- A color palette for icons of files with common extensions was also sourced from [nvim-web-devicons](https://github.com/nvim-tree/nvim-web-devicons); for icons of files not falling under this category said icons will be styled based on the `LS_COLORS` configuration of its associated file.
In order for glyphs/icons to display properly your terminal emulator must be …
> Icon support

- src/cli.rs
Closes https://github.com/solidiquis/erdtree/issues/22
- `--ignore-git` added to prevent traversal of `.git` when showing hidden files.
- `Dylan »Forklift Operator« DPC —` & `Aranea` on Rust Discord for the UX input <3
> --ignore-git

- src/fs/erdtree/node.rs
- src/icons.rs
Fix issue where there's extra fill to the left of the disk usage of symlinks.
> fix extra whitespace problem when displaying symlink name

- src/fs/erdtree/node.rs
Closes https://github.com/solidiquis/erdtree/issues/30
Panics occur when file-names contain non-unicode sequences. This PR fixes the issue by doing lossy conversion of `OsStr` to Cow<'_, str>.
> lossy unicode conversion of file name

- src/fs/erdtree/node.rs
Closes https://github.com/solidiquis/erdtree/issues/31
Fix is simple: When file-name can't be ascertained as in the case of `/` we'll fall back on just using the path.
> Use path when file-name can't be ascertained

- Cargo.lock
- Cargo.toml
- src/cli.rs
- src/fs/erdtree/disk_usage.rs
- src/fs/erdtree/mod.rs
- src/fs/erdtree/node.rs
- src/fs/erdtree/order.rs
- src/fs/erdtree/tree/mod.rs
- src/icons.rs
- tests/sort.rs
```
-d, --disk-usage <DISK_USAGE>  Print physical or logical file size [default: logical] [possible values: logical, physical]
-s, --sort <SORT>              Sort-order to display directory content [default: none] [possible values: name, size, size-rev, none]
```
- Adds option to view either logical or physical disk usages with logical being the default:
- Sorting by file size by defaults prints the largest files towards the bottom. People usually are more interested the larger files and it's annoying to have to scroll up for larger file-trees.
- Added ability to sort by file size in reverse
> Disk usage

- src/fs/erdtree/node.rs
- src/fs/erdtree/tree/mod.rs
- src/fs/inode.rs
- src/fs/mod.rs
When multiple hardlinks exist in a file-tree that point to the same underlying inode only the first one is shown and taken into account as to not give bloated and inaccurate measurements of disk usage.
> Handle hardlinks

- src/cli.rs
- src/fs/erdtree/disk_usage.rs
- src/fs/erdtree/node.rs
- src/fs/erdtree/tree/mod.rs
- tests/glob.rs
- tests/level.rs
- tests/sort.rs
- tests/symlink.rs
Added an option to adjust the scale (numbers after the decimal point) used for disk usage reports:
```
-n, --scale <NUM>              Total number of digits after the decimal to display for disk usage [default: 2]
```
> support scale for disk usage report

- src/fs/erdtree/tree/mod.rs
- src/fs/inode.rs
Minor optimization: Don't hash inode properties if `nlinks` is 1 i.e. there is only 1 hardlink.
> don't hash inode if number of links is 1

- README.md
- src/cli.rs
- src/fs/erdtree/node.rs
- src/fs/erdtree/tree/mod.rs
- tests/suppress_size.rs
> Add option to suppress size from being printed

- README.md
- src/render/context/mod.rs
- src/render/disk_usage.rs
- src/render/mod.rs
- src/render/node.rs
- src/render/order.rs
- src/render/tree/mod.rs
- src/render/tree/node.rs
Added an option to toggle between binary and SI prefixes when reporting disk usage.
```
-p, --prefix <PREFIX>          Display disk usage as binary or SI units [default: bin] [possible values: bin, si]
```
> Option to toggle SI and Binary prefix

- src/render/context/mod.rs
- src/render/disk_usage.rs
- src/render/mod.rs
- src/render/tree/mod.rs
- src/render/tree/node.rs
Closes https://github.com/solidiquis/erdtree/issues/45
Fixed bug where `--ignore-git` wasn't ignoring `.git` when `-H` was used.
> fix --ignore-git

- Cargo.lock
- Cargo.toml
- src/render/context/mod.rs
- src/render/context/test.rs
- tests/data/.erdtreerc
Fixes bug where boolean arguments aren't properly read in from the config file.
> Config bug

- src/render/context/config.rs
Closes https://github.com/solidiquis/erdtree/issues/64 and https://github.com/solidiquis/erdtree/issues/63
The configuration file can now be placed in more locations:
- `$ERDTREE_CONFIG_NAME`
- `$XDG_CONFIG_HOME/erdtree/.erdtreerc`
- `$XDG_CONFIG_HOME/.erdtreerc`
- `$HOME/.config/erdtree/.erdtreerc`
- `$HOME/.erdtreerc`
> additional locations for config file

- README.md
Packaged for NetBSD and merged into the main repo, [commit message](http://mail-index.netbsd.org/pkgsrc-changes/2023/03/15/msg270988.html)
> Add NetBSD instructions

- Cargo.lock
- Cargo.toml
- src/main.rs
- src/render/context/mod.rs
closes #79
Adds a ```--completions``` flag for generating shell completions
> Add support for generating shell completions

- src/render/tree/node.rs
useful for example when a directory's name ends with an extension
- before:
- after:
> fix: check filetype before extension

- Cargo.lock
- Cargo.toml
- src/render/context/mod.rs
- src/render/disk_usage.rs
- src/render/tree/mod.rs
- src/render/tree/node.rs
- src/render/tree/visitor.rs
- https://github.com/solidiquis/erdtree/issues/89
- `Tree` is now a wrapper around an [index tree](https://docs.rs/indextree/latest/indextree/) as opposed to a heap-based tree structure where every `Node` holds a `Vec` of its children. The benefits of this are less indirection and therefore less trips to the heap as well as better CPU cache locality.
- Printing of the `Tree` is now done iteratively as opposed to recursively.
> [Optimization] - Custom visitor, index tree, scoped thread

- src/render/tree/ui.rs
- https://github.com/solidiquis/erdtree/issues/66
Shoutout to @fawni for figuring this one out `(♡ヮ♡)`
> fix issue where ansi escapes were being printed raw on windows

- .github/workflows/publish.yml
[Github Action Log](https://github.com/Tlntin/erdtree/actions/runs/4468692975/jobs/7849771800)
[Release url](https://github.com/Tlntin/erdtree/releases/tag/v1.6.0)
The screenshot is as follows, the windows version number is normal.
> Fix windows can not recognize the tag version when publishing

- Cargo.lock
- Cargo.toml
- src/render/context/mod.rs
`num_cpus` shouldn't be needed since `available_parallelism()` has been stable since Rust 1.59
> Swap `num_cpus` for `available_parallelism`

- .github/workflows/test.yml
Fix the problem that test actions cannot upload windows binary files
add the function of custom form to set tag version.
By default, pre release will be generated, if you want change it, you can refer to this [link](https://github.com/ncipollo/release-action#release-action)
> Fix the problem that test actions cannot upload windows binary files, add the function of custom form to set tag version.

- src/render/context/mod.rs
- src/render/tree/mod.rs
Setting default thread count to `available_parallelism` takes us way past the point of diminishing returns which is actually detrimental to performance.
`3` seems to be the sweet spot I've found across various SSDs and HDDs.
For more information about how parallelism affects disk reads checkout [this link](https://pkolaczk.github.io/disk-parallelism/).
```
┌─ code
└ 🧋 time et -l 1 -H -i -t 1 --no-config
code (125.46 GiB)
├─ ruby (32.87 KiB)
├─ advent_of_code (3.81 MiB)
├─ lua (21.02 KiB)
├─ homebrew-tap (33.93 KiB)
├─ rust (6.52 GiB)
├─ projects (118.94 GiB)
├─ test (25.55 KiB)
├─ .DS_Store (6.00 KiB)
└─ golf (2.30 KiB)
et -l 1 -H -i -t 1 --no-config  1.06s user 0.88s system 121% cpu 1.597 total
┌─ code
└ 🧋 time et -l 1 -H -i -t 2 --no-config
code (125.46 GiB)
├─ ruby (32.87 KiB)
├─ …
```
> Reduce default thread count

- Cargo.lock
- Cargo.toml
- src/fs/inode.rs
- src/icons.rs
- src/main.rs
- src/render/context/config.rs
- src/render/context/mod.rs
- src/render/context/test.rs
- src/render/disk_usage.rs
- src/render/order.rs
- src/render/tree/error.rs
- src/render/tree/mod.rs
- src/render/tree/node.rs
- src/render/tree/visitor.rs
- src/utils.rs
I have added Clippy into the project and applied a few of the fixes while silencing other ones.
I Also removed the crossbeam crate, since it's merged into the standard library since Rust 1.67.0.
To improve ergonomics through elimination of boilerplate code and simplification of adding new errors, I have added the thiserror crate.
> Application of Clippy lints and possible improvement in development ergonomics

- src/render/context/config.rs
I have deleted this if-let branching, so that function becomes oneliner. I would use `flat_map` with closure, but it seems it is not welcomed here :)
I didn't test this changes, so I expect to be supervised by CI.
> Remove branching in `read_config_to_string`

- README.md
- src/render/context/test.rs
Corrects some typos in the repository.
> Fix some typos

- src/render/context/mod.rs
- tests/report.rs
While playing around with `et` I was wondering why `--human` had no effect until I noticed that it's supposed to be used in combination with `--report`.
This adds the `requires` tag to `--human` and `--file-name` in order to print a useful error message when these options are used without `--report`.
A better alternative approach would be to implement something like: `et --report=human,file-name`, but I think that's only possible with clap's Builder API.
> add clap requires to flags that depent on --report

- src/render/tree/mod.rs
- tests/glob.rs
- tests/prune.rs
Closes https://github.com/solidiquis/erdtree/issues/115
> Prevent panic when `--prune` is used with `--glob` which results in empty match set

- Cargo.lock
- Cargo.toml
- src/icons.rs
- src/render/context/mod.rs
- src/render/tree/node/mod.rs
> remove ansi escapes for default icon

- src/ansi.rs
- src/fs/permissions/class.rs
- src/fs/permissions/file_type.rs
- src/fs/permissions/mod.rs
- src/fs/permissions/test.rs
- src/main.rs
- src/render/context/file.rs
- src/render/context/mod.rs
- src/render/context/sort.rs
- src/render/context/test.rs
- src/render/disk_usage/file_size.rs
- src/render/styles/mod.rs
- src/render/tree/mod.rs
- src/render/tree/node/cmp.rs
- src/render/tree/node/display/mod.rs
- src/render/tree/node/display/presenters.rs
- src/render/tree/node/mod.rs
- tests/hardlink.rs
This commit is trying to get rid of the silenced Clippy warnings and fix them. The three Clippy lints “cast_precision_loss”, “cast_sign_loss” and “cast_possible_truncation” are not really fixable and just in the way, which is why they are now muted in the whole project. The “struct_excessive_bool” lint has not been fixed, as it would probably require a breaking change.
I will start an issue, discussing this.
> refactor: :recycle: Applying Clippy lints

- src/fs/xattr.rs
In order to support *BSD especially.
Fixes #157 
I love erdtree so much, it's quite fast and readable!!
> Use 3 arguments listxattr() on non-macOS Unix

- Cargo.lock
- Cargo.toml
- README.md
- src/render/context/config.rs
- src/render/tree/node/display/mod.rs
Windows by default does not set or use the $HOME environment variable. This commit adds a Windows specific branch which tries to locate the config file in %APPDATA%/erdtree/.erdtreerc instead
Fixes #152
> Added Windows specific config location

- CHANGELOG.md
- README.md
- src/fs/permissions/file_type.rs
- src/render/context/color.rs
- src/render/context/dir.rs
- src/render/context/mod.rs
- src/render/tree/node/cmp.rs
- tests/sort.rs
Closes https://github.com/solidiquis/erdtree/issues/149
```
--dir-order <DIR_ORDER>      Sort directories before or after all other file types [default: none] [possible values: none, first, last]
```
```
--dir-order <DIR_ORDER>
Sort directories before or after all other file types
[default: none]
Possible values:
- none:  Directories are ordered as if they were regular nodes
- first: Sort directories above files
- last:  Sort directories below files
```
> extra granularity for dir ordering

- README.md
- src/render/context/config.rs
- src/render/context/dir.rs
- src/render/tree/node/cmp.rs
- src/render/tree/node/mod.rs
- tests/sort.rs
Closes https://github.com/solidiquis/erdtree/issues/148
> show symlink target's path, not just name

- README.md
- src/context/mod.rs
- src/context/time.rs
- src/render/grid/cell.rs
add support for specifying a format for timestamps (`--time-format`) in `--long` mode. the formats are inspired by [the git implementation](https://git-scm.com/docs/git-log#Documentation/git-log.txt---dateltformatgt).
i was unsure of what flag to use, but since you used `--time` over `--date`, and therefore `--time` was already taken by something else, i chose the more explicit `--time-format` flag.
i chose to add the formats `iso`, `iso-strict` and `short`, the latter two strictly following their implementation in git, with `iso` dropping the time zone specifier entirely (since the time zone is local-only anyway), but i made it so you should be able to easily expand to more options if needed.
the old format is still the default or can be explicitly specified with `--time-format default`. …
> add support for specifying time formats

- Cargo.lock
- Cargo.toml
- src/context/column.rs
- src/context/mod.rs
- src/disk_usage/file_size/byte.rs
- src/disk_usage/file_size/mod.rs
- src/disk_usage/units.rs
- src/fs/mod.rs
- src/fs/ug.rs
- src/main.rs
- src/render/grid/cell.rs
- src/render/grid/mod.rs
- src/render/long/mod.rs
- src/render/mod.rs
- src/styles/mod.rs
- src/tree/mod.rs
- src/tree/node/mod.rs
- src/tree/node/unix.rs
- tests/flat.rs
- Default long view now includes permissions, owner, and modification time. `ino`, `nlinks`, and `group` are optional.
- Added support file file owner and group.
- Human readable byte metric is now 1-scale i.e. one digit after the decimal
> support for user and group

- Cargo.lock
- Cargo.toml
- src/context/mod.rs
- src/disk_usage/file_size/byte.rs
- src/main.rs
- src/progress.rs
- src/render/layout/regular.rs
- src/tree/mod.rs
- tests/sort.rs
Adds a progress indicator and an optional `--no-progress` to disable it.
The progress indicator will not be enabled if stdout is not a tty.
https://github.com/solidiquis/erdtree/assets/45523555/ecc3793c-58a7-4da3-82e3-352fd4af76f6
> progress bar

- src/fs/ug.rs
- src/tty/mod.rs
Closes https://github.com/solidiquis/erdtree/issues/189
When a user or group isn't valid `errno` doesn't get set which causes a null pointer dereference. This PR does a null pointer check and returns an error if user or group is invalid.
> Fix segmentation fault when invalid group or user

- src/tree/mod.rs
Some folks like to use `erdtree` as an `ls` replacement but because `erdtree` always does a full-depth traversal when reading entries from either disk or cache it was quite slow to get the first depth level of directory entries even if directory size is suppressed.
This PR makes it such that `$ erd --suppress-size --level 1` only reads root's entries using only a single-thread (regardless of `-T, --threads`) so that results are available almost instantaneously.
> Suppress size performance

- README.md
- src/context/time.rs
Added aliases for `--time` enums:
```
--time <TIME>
Which kind of timestamp to use; modified by default
Possible values:
- create: Time created (alias: ctime)
- access: Time last accessed (alias: atime)
- mod:    Time last modified (alias: mtime)
```
> Time aliases

- example/.erdtree.toml
- rustfmt.toml
- src/context/args.rs
- src/context/config/rc.rs
- src/context/config/toml/mod.rs
- src/context/error.rs
- src/context/mod.rs
- src/disk_usage/file_size/byte.rs
- src/icons/fs.rs
- src/main.rs
- src/progress.rs
- src/render/grid/cell.rs
- src/render/layout/regular.rs
- src/render/long/mod.rs
- src/tree/node/cmp.rs
- src/tree/node/mod.rs
- src/tree/visitor.rs
Removes some dirty hacks that supported the use of a config file.
Logic that reconciles arguments between the CLI and a potential config file has now been moved over into a trait with more rigorous argument processing as to remove hacks and make things less error prone.
> Argument reconciliation trait

- Cargo.lock
- Cargo.toml
- src/main.rs
- src/progress.rs
- src/tree/error.rs
- src/tree/mod.rs
- src/tree/visitor.rs
- src/tty/mod.rs
Added `ctrlc` handler to restore cursor visibility in the case where the progress message is enabled.
> Restore tty settings

- CHANGELOG.md
- Cargo.lock
- Cargo.toml
- README.md
- src/context/mod.rs
- src/main.rs
- src/progress.rs
Emergency patch for https://github.com/solidiquis/erdtree/issues/214
> Stdout deadlock fix

- src/progress.rs
Resolves https://github.com/solidiquis/erdtree/issues/214
> remove priority mailbox; fix stdout deadlock

- README.md
- src/context/mod.rs
- src/main.rs
- src/progress.rs
- src/tree/mod.rs
Closes https://github.com/solidiquis/erdtree/issues/219
There was a race between printing to stderr and the cleanup function clearing the current cursor line. This PR removes atomic shared ownership of the progress indicator and instead passes around a channel so that all requests to run a cleanup funnels to a single location: The progress indicator's thread.
We then join that thread to the main-thread before printing any sort of output whether it be an error message or the actual result.
This is better design overall and I should have done this from the start.
> Fixed race to print

- src/tree/mod.rs
#208 
- Do not respect .gitignore **...and global .gitignore files**
**Change Summary**
- The issue is due to the presence of a global .gitignore file; the symlink was just the victim by chance. Currently, globally ignored files will continue to be removed regardless of flag: -i, --no-ignore. Syncing both global and local .gitignores better addresses the user request.
**Change to Code**
- specifying git_global() method with ignore context to WalkBuilder struct to match the (-i, --no-ignore) flag's use case.
> ensure global .gitignore to sync with git_ignore flag

- src/context/args.rs
- src/context/config/toml/error.rs
- src/context/config/toml/mod.rs
I noticed that syntax errors in the TOML config file would result in a "file not found" style error message which can be rather confusing. So here's a proposal to change that.
> Display config file formatting errors

- src/tree/node/mod.rs
Previously, the unix extended attributes are always read no matter what. This is maybe not ideal, as it is very expensive to call for files which we will not display and leads to significantly (~300x with level = 2) worse runtimes recursing large directories. This is fixed by only calling `unix::Attrs::from` when it is a file which is going to be displayed.
This is my first PR here, so if I've missed anything please let me know.
These are run with the path being my home directory, which consists of (per `erd`) 11650 directories, 124225 files, and 132 links. The command run is `time erd -l --no-config -L 2 ~` for both cases, and all times are averaged over 5 runs.
| Executed in | 81.01 secs |
|:-----------------:|:---------------:|
| usr time       | 10.83 secs |
| sys time       | 15.58 …
> Improve performance when using `--long`
